package gentags

import (
	"fmt"
	"gowizard/builder/model/system"
	"gowizard/util"
	"strings"
)

type Custom struct {
	modelInstance *system.Model
	layer         *system.Layer
}

const (
	defaultCustom = "//todo: generated by wizard and should be implemented\npanic(\"implement me\")\n"
	defaultError  = "//todo: generated by wizard and there are no next layer\npanic(\"implement me\")\n"
)

func NewCustom(layer *system.Layer, modelInstance *system.Model) *Custom {
	return &Custom{
		layer:         layer,
		modelInstance: modelInstance,
	}
}

func (c *Custom) Create() string {
	if c.layer.NextLayer == nil {
		return defaultError
	}

	return fmt.Sprintf("return %s.%s.Create%s(%s)\n",
		strings.ToLower(string([]rune(c.modelInstance.Name)[0])),
		c.layer.NextLayer.Name,
		c.modelInstance.Name,
		util.MakePrivateName(c.modelInstance.Name)+"Model")
}

func (c *Custom) Read() string {
	if c.layer.NextLayer == nil {
		return defaultError
	}

	return fmt.Sprintf("return %s.%s.Read%s(%s)\n",
		strings.ToLower(string([]rune(c.modelInstance.Name)[0])),
		c.layer.NextLayer.Name,
		c.modelInstance.Name,
		util.MakePrivateName(c.modelInstance.Name)+"Model")
}

func (c *Custom) Update() string {
	if c.layer.NextLayer == nil {
		return defaultError
	}

	return fmt.Sprintf("return %s.%s.Update%s(%s)\n",
		strings.ToLower(string([]rune(c.modelInstance.Name)[0])),
		c.layer.NextLayer.Name,
		c.modelInstance.Name,
		util.MakePrivateName(c.modelInstance.Name)+"Model")
}

func (c *Custom) Delete() string {
	if c.layer.NextLayer == nil {
		return defaultError
	}

	return fmt.Sprintf("return %s.%s.Delete%s(%s)\n",
		strings.ToLower(string([]rune(c.modelInstance.Name)[0])),
		c.layer.NextLayer.Name,
		c.modelInstance.Name,
		util.MakePrivateName(c.modelInstance.Name)+"Model")
}

func (c *Custom) Custom() string {
	return defaultCustom
}
